### ISSUE TITLE
@keyframes and @media conversion bug

### ISSUE THREAD

**Issue by zoxon** [lnikell/css-converter#13]
## keyframes

This code

``` css
@keyframes remodal-opening-keyframes {
  from {
    transform: scale(1.05);

    opacity: 0;
  }
  to {
    transform: none;

    opacity: 1;
  }
}

@keyframes remodal-closing-keyframes {
  from {
    transform: scale(1);

    opacity: 1;
  }
  to {
    transform: scale(0.95);

    opacity: 0;
  }
}

@keyframes remodal-overlay-opening-keyframes {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}

@keyframes remodal-overlay-closing-keyframes {
  from {
    opacity: 1;
  }
  to {
    opacity: 0;
  }
}
```

Converts to 

``` styl
    to
        transform none
        opacity 1
        transform scale(0.95)
        opacity 0
        opacity 1
        opacity 0

    @keyframes
        remodal-opening-keyframes
            from {
    transform scale(1.05)
            opacity 0

    }
        @keyframes
            remodal-overlay-closing-keyframes
                from {
    opacity 1
            remodal-closing-keyframes
                from {
    transform scale(1)
                opacity 1
            remodal-overlay-opening-keyframes
                from {
    opacity 0
```
## Media

This code

``` css
@media only screen and (min-width: 641px) {
  .remodal {
    max-width: 700px;
  }
}
```

Converts to 

``` styl
    @media
        only
            screen
                and
                    (min-width
                        &:
                            641px)
                                .remodal {
    max-width 700px

```

My config, system, sublime

``` json
{
    "colon": false
}
```

Windows 7 x64

Sublime Text 3 build 3103 x64
